### ISSUE TITLE
Could you add the SDcard function to this board?

### ISSUE THREAD

**Issue by ywz978020607** [mcauser/BLACK_F407ZE#1]
hello，these days I need the stm32f407zgt6 using mpy, and my board is same with yours. I am really thanks to your contribution of the codes and pin  fuctions, Could you please add the sdcard in this board function?Noticing that sdcard is (0),and I changed that to (1) and sdcard pin removed(#), but I still can't use the sdcard . Please update with this, and I will really thanks for that!

**Comment by mcauser** [comment]
This board is the ZET6. The ZGT6 board is over here: https://github.com/mcauser/BLACK_F407ZG

The boards do not have SD card detect pins. There's an upstream PR to fix this:
https://github.com/micropython/micropython/pull/5185
